linux_task:
  name: "arm cimg/base:edge"
  arm_container:
    image: cimg/base:edge
    cpu: 1
    memory: 1G
  timeout_in: 5m
  script:


    # https://github.com/ardera/flutter-engine-binaries-for-arm
    #
    # get manually from (but I should automate this)
    #    latest stable
    #    https://github.com/flutter/flutter/blob/stable/bin/internal/engine.version
    #    (ONLY 7MB - will download (including .so and flutter headers)
    #
    # git hash is in
    - curl -v -o engine.version -L https://github.com/flutter/flutter/blob/stable/bin/internal/engine.version
    - export VERSION=`cat engine.version`
    - echo $VERSION

