linux_task:
  name: "cimg/base:edge"
  # name: "cirrusci/flutter:latest"
  arm_container:
    image: cimg/base:edge
    # arm_container: Error starting command: fork/exec /usr/bin/bash: exec format error
    # image: cirrusci/flutter:latest
    cpu: 1
    memory: 1G
  timeout_in: 5m
  script:
    - uname -a
    - whoami
    - ls -alrt
    - sudo apt-get install dnf
    - sudo dnf install snapd
    # - sudo echo ${PATH}  || true
    - echo ${PATH}  || true
    # - sudo which sudo  || true
    # - sudo which yum   || true
    # - sudo which snap  || true
    # - sudo which dart  || true
    - dart --version || true
    # - sudo which flutter || true
    - flutter --version || true
    # - sudo ls -l /usr/bin
    # - sudo apt-get update
    # - reboot
    # - sudo apt-get install snapd
    # - sudo which snap  || true
    # - sudo snap --version
    # - sudo snap install core
    # - sudo snap install flutter --classic
    # - flutter --version

