linux_task:
  name: "openjdk:latest"
  arm_container:
    image: cimg/openjdk
    cpu: 1
    memory: 1G
  timeout_in: 5m
  script:
    - uname -a
    - ls -alrt
    - echo ${PATH} || true
    - which java  || true
    - which sudo  || true
    - which yum   || true
    - which snap  || true
    - which dart  || true
    - which flutter || true
