linux_task:
  name: "cimg/base:edge"
  arm_container:
    image: cimg/base:edge
    cpu: 1
    memory: 1G
  timeout_in: 5m
  script:
    - uname -a
    - whoami
    - ls -alrt
    - sudo echo ${PATH} || true
    - sudo which sudo  || true
    - sudo which yum   || true
    - sudo which snap  || true
    - sudo which dart  || true
    - sudo which flutter || true
    - sudo ls -l /usr/bin
    - sudo apt-get update
    - sudo apt-get install snapd
    - sudo reboot
    - sudo which snap  || true
    - sudo snap --version
    - sudo snap install core
    - sudo snap install flutter --classic

