
version: 1.0.{build}.{branch}
clone_depth: 1

environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022

  matrix:
    - Platform: x64

init:
- echo init

install:
- echo install_script

build_script:
- echo build_script
- echo ALPHA > ALPHA.txt

artifacts:
- path: 'ALPHA.txt'
  name: ALPHA

deploy:
  - provider: GitHub
    release: 100
    draft: false
    prerelease: false
    artifact: ALPHA
    auth_token:
      # Token of Dave
      ## secure: nasXR/dCMdQmmouYtN0t1/9jilLmOA6E5EsGoP6Td5yvp3JK4QPfZO0BEVzMeXW1
      # Token of Andre
      secure: DpxrjrmF0pQsm3G/F8m7EDVz6yhBQhlwXWOtqxgQTmUMiofL1PZD+9Q1dAqyKh9Z


