
version: 1.0.{build}.{branch}
clone_depth: 1

environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

  matrix:
    - Platform: x64

init:
- echo init
- "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property productId
- "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property catalog_productLineVersion

install:
- echo install_script

build_script:
- echo build_script
