
version: 1.0.{build}.{branch}
clone_depth: 1

environment:

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      Platform: x64

init:
- echo init

install:
- echo install_script

build_script:
- echo build_script
- mkdir Play
- cd Play
- mkdir Play2
- cd Play2
- ps: |
    Set-PSDebug -Trace 2
    $MIKTEX_MIRROR = "https://miktex.org/download/win/basic-miktex-x64.exe"
    & "C:\Program Files\Git\mingw64\bin\curl.exe" -o ../basic-miktex-x64.exe -L $MIKTEX_MIRROR
    
