
version: 1.0.{build}.{branch}
clone_depth: 1

environment:

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      Platform: x64

init:
- echo init

install:
- echo install_script

build_script:
- echo build_script
- bash -login -c 'alias'
- echo build_script >> deploy_test.txt

artifacts:
  - path: deploy_test.txt
    name: deploy_test

deploy:
  - provider: GitHub
    release: "%APPVEYOR_PROJECT_SLUG%_%appveyor_build_version%
    auth_token:
      secure: KzS1DumC2yBg2LGN9x3AemHFOjAdp+rD58rW5aGGpwW4Pfdwdm7AmRpYKprPY8Gs
    artifact: deploy_test
    draft: false
    prerelease: false
    
