
version: 1.0.{build}.{branch}
clone_depth: 1

# TRYING TO FIGURE OUT THIS ERROR
# Deploying using FTP provider
# Cannot connect SFTP server: Failed to negotiate key exchange algorithm.

environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022

  matrix:
    - Platform: x64

init:
- echo init

install:
- echo install_script

build_script:
- echo build_script
- echo ALPHA > ALPHA.txt

deploy_script:
- cmd: |
    choco install -y winscp
    echo open sftp://andremikulec,andremikulec.u:%FTP_PSW%@frs.sourceforge.net/ > ftp.txt 2>&1 || date /t
    echo put ALPHA.txt /home/pfs/project/andremikulec/ >> ftp.txt
    echo exit >> ftp.txt
    set PATH=C:\Program Files (x86)\WinSCP;%PATH%
    winscp.com /script=ftp.txt

artifacts:
- path: 'ALPHA.txt'
  name: ALPHA

# deploy:
#   - provider: FTP
#     host: frs.sourceforge.net
#     protocol: sftp
#     # https://sourceforge.net/projects/andremikulec/files/
#     username: andremikulec,andremikulec.u
#     password:
#       secure: AZOInJ/FinCYx+tbyshJR5VWUISswlz5yiGDqfgEXLg=
#     artifact: ALPHA
#     folder: /home/pfs/project/andremikulec
#     application:
#     active_mode: false

