
version: 1.0.{build}.{branch}
clone_depth: 1

# TRYING TO FIGURE OUT THIS ERROR
# Deploying using FTP provider
# Cannot connect SFTP server: Failed to negotiate key exchange algorithm.

environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022

  matrix:
    - Platform: x64

init:
- echo init

install:
- echo install_script

build_script:
- echo build_script
- echo ALPHA > ALPHA.txt

after_build:

- cmd: |
    choco install -y winscp
    echo open sftp://andremikulec,andremikulec.u:%FTP_PSW%@frs.sourceforge.net/ -hostkey="acceptnew" > ftp.txt 2>&1 || date /t
    echo put ALPHA.txt /home/frs/project/andremikulec/ >> ftp.txt
    echo exit >> ftp.txt
    set PATH=C:\Program Files (x86)\WinSCP;%PATH%
    winscp.com /script=ftp.txt

deploy:

  - provider: GitHub
    release: v1.0
    auth_token:
      secure: O4OTdJVY47/Ju0HtC3lEUOtmgFrdOiNCZyHPHi3FPDdJUmnqdsDhPGtJi+j+cLgy
    artifact: ALPHA
    draft: false
    prerelease: false
    on:
      branch: master

artifacts:
- path: 'ALPHA.txt'
  name: ALPHA

# deploy:
#   - provider: FTP
#     host: frs.sourceforge.net
#     protocol: sftp
#     # https://sourceforge.net/projects/andremikulec/files/
#     username: andremikulec,andremikulec.u
#     password:
#       secure: AZOInJ/FinCYx+tbyshJR5VWUISswlz5yiGDqfgEXLg=
#     artifact: ALPHA
#     folder: /home/pfs/project/andremikulec
#     application:
#     active_mode: false

