
name: The_Great_Name

on: push

jobs:

  information_env:
    name: Knowledge About env
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context global data
        run:   export
        shell: bash

  information_github:
    name: Knowledge About github
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context global data
        run:   echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

  information_ubuntu:
    name: Knowledge About runner ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Dump runner context global data
        run:   echo "$RUNNER_CONTEXT"
        shell: bash
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}

  # GITHUB_ENV	
  # The path on the runner to the file that sets environment variables 
  # from workflow commands. 
  # This file is unique to the current step 
  # and changes for each step in a job. 
  #
  setinformation:
    name: Knowledge New
    runs-on: ubuntu-latest
    steps:
      - name: Set new global data USER_SOMETHING
        run: |
          echo "USER_SOMETHING=something" >> $GITHUB_ENV
          echo "USER_GIT_TAG=`git describe --tags --abbrev=0 2>/dev/null || true`" >> $GITHUB_ENV
          echo "USER_GIT_COMMIT=`rev-parse HEAD 2>/dev/null || true`" >> $GITHUB_ENV
          cat $GITHUB_ENV
          # not SEEING anything
          export | grep USER_ 2>/dev/null || true
        shell: bash
          
  build:
    name: Build New
    runs-on: ubuntu-latest
    steps:
      - name: Set new global data
        run: |
          date > README.txt
        shell: bash

  release:
    name: Release Me
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        replacesArtifacts: true
        commit: ${{ env.USER_SHA }}
        tag: ${{ env.USER_GITHUB_REF_NAME }}
        artifacts: "README.txt"
        token: ${{ secrets.ACTIONS_CREATE_RELEASE_REPO_SECRET }}
    env:
      USER_GITHUB_SHA: ${{ github.sha }}
      USER_GITHUB_REF_NAME: ${{ github.ref_name }}
