
name: The_Great_Name

on: push

jobs:

  information_env:
    name: Knowledge About env
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context global data
        run:   export
        shell: bash

  information_github:
    name: Knowledge About github
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context global data
        run:   echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

  information_ubuntu:
    name: Knowledge About runner ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Dump runner context global data
        run:   echo "$RUNNER_CONTEXT"
        shell: bash
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}

  setinformation:
    name: Knowledge New
    runs-on: ubuntu-latest
    steps:
      - name: Set new global data USER_SOMETHING
        run: |
          echo "USER_SOMETHING=something" >> $GITHUB_ENV
      - name: Set new global data USER_GIT_TAG
        run: |
          echo "USER_GIT_TAG=`git describe --tags --abbrev=0 2>/dev/null || true`" >> $GITHUB_ENV
      - name: Set new global data USER_GIT_COMMIT
        run: |
          echo "USER_GIT_COMMIT=`rev-parse HEAD 2>/dev/null || true`" >> $GITHUB_ENV
      - name: Print Output
        run: |
          cat $GITHUB_ENV
        shell: bash
          
  information_env_2:
    name: Knowledge About env 2
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context global data
        run:   export
        shell: bash
          
  build:
    name: Build New
    runs-on: ubuntu-latest
    steps:
      - name: Set new global data
        run: |
          date > README.txt
        shell: bash

  release:
    name: Release Me
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        replacesArtifacts: true
        commit: HEAD
        tag: THE_CURRENT_RELEASE
        artifacts: "README.txt"
        token: ${{ secrets.ACTIONS_CREATE_RELEASE_REPO_SECRET }}
