
name: The_Great_Name

on: push

jobs:

  information_env:
    name: Knowledge About env
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context global data
        run:   echo "$ENV_CONTEXT"
        shell: bash
        env:
          ENV_CONTEXT: ${{ toJson(env) }}
          
  information_github:
    name: Knowledge About github
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context global data
        run:   echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

  information_ubuntu:
    name: Knowledge About runner ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Dump runner context global data
        run:   echo "$RUNNER_CONTEXT"
        shell: bash
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}

  setinformation:
    name: Knowledge New
    runs-on: ubuntu-latest
    steps:
      - name: Set new global data
        run: |
          echo "USER_GIT_TAG=`git describe --tags --abbrev=0 2>/dev/null || true`" >> $GITHUB_ENV
          echo "USER_GIT_COMMIT=`rev-parse HEAD 2>/dev/null || true`" >> $GITHUB_ENV
          
  build:
    name: Knowledge New
    runs-on: ubuntu-latest
    steps:
      - name: Set new global data
        run: |
          date > README.txt

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        replacesArtifacts: true
        commit: ${{ env.USER_GIT_COMMIT }}
        tag: THE_CURRENT_RELEASE
        artifacts: "README.txt"
        token: ${{ secrets.GITHUB_ACTIONS_CREATE_RELEASE_REPO }}

